Update migration.md
PrestaShop/docs pull request #1016
Opened 2021-05-26 10:02 UTC by GabrieleMartini

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Fix typo
| Fixed ticket? | Fixes #{issue number here} if there is a related issue

2021-05-26 10:15 UTC, PululuK requested changes
Hi @GabrieleMartini 
You are on fire 🔥
But, I see that most of your Pr is for the same file. 
Could you please put everything in one PR?

2021-05-26 10:24 UTC, GabrieleMartini commented
> Hi @GabrieleMartini
> You are on fire fire
> But, I see that most of your Pr is for the same file.
> Could you please put everything in one PR?

Ok @PululuK thank you

2021-06-05 20:05 UTC, matks requested changes

2021-06-05 20:05 UTC, matks commented on src/content/1.7/basics/keeping-up-to-date/migration.md
> +Also, make sure the IDs of your langs matches on the source shop.
There are many ID so it's plural => `match` is good, not `matches`

2021-06-05 20:05 UTC, matks commented
@GabrieleMartini Thank you for the proof-reading but it seems this PR actually does not fix an issue 😉 so I close it

2021-06-05 20:05 UTC, closed without merging