Update migration.md
PrestaShop/docs pull request #1021
Opened 2021-05-26 10:19 UTC by GabrieleMartini

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Please be specific when describing the PR. What did you add, why did you submit it?
| Fixed ticket? | Fixes #{issue number here} if there is a related issue

2021-05-26 10:20 UTC, PululuK requested changes
See https://github.com/PrestaShop/docs/pull/1016#pullrequestreview-668840752a

2021-06-05 20:04 UTC, matks requested changes

2021-06-05 20:04 UTC, matks commented on src/content/1.7/basics/keeping-up-to-date/migration.md
> +own tools for migrations, other ways exists to get the business data.
There are many "other ways" so plural is expected

2021-06-05 20:04 UTC, matks commented
@GabrieleMartini Thank you for the proof-reading but it seems this PR actually does not fix an issue 😉 so I close it

2021-06-05 20:04 UTC, closed without merging