Remove addons advertising in themes introduction.
PrestaShop/docs pull request #1182
Opened 2021-10-13 06:27 UTC by jf-viguier

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 8.x
| Description?  | Remove addons publicity.
| Fixed ticket? | no

2021-10-13 06:41 UTC, kpodemski commented
I'm not sure about this change. I would still recommend Addons Marketplace and maybe just add "and others" here and there.

WDYT @ttoine @eternoendless ?

2021-10-13 06:47 UTC, jf-viguier commented
The dev doc is for the open source version or prestashop corp version ?
Open source version shouldn't promote addons more than another

2021-10-13 06:51 UTC, Progi1984 commented on themes/_index.md
> +Several marketplaces are availables to buy prestashop themes.
```suggestion
Several marketplaces are available to buy PrestaShop themes.
```

2021-10-13 06:51 UTC, Progi1984 reviewed
@jf-viguier Thanks. A small feedback

2021-10-13 06:53 UTC, Progi1984 approved these changes

2021-10-13 08:36 UTC, eternoendless commented
I'm not sure if the documentation needs to be 100% neutral. One option would be to list "partner" marketplaces. After all, PrestaShop SA still largely funds PrestaShop development. WDYT @ttoine?

2021-10-13 08:36 UTC, eternoendless requested changes
Blocking this until a decision is made

2021-10-13 09:08 UTC, andromaque commented
> After all, PrestaShop SA still largely funds PrestaShop development.
And there are also other contributors who spend a lot of time and efforts in this project, so they should be allowed to also advertise in the source code or documentation? I think it should remain neutral, advertise all you want in the PrestaShop corp site, on ads or whatever, but leave the project free of publicity.

2021-10-13 09:25 UTC, jf-viguier commented
"are sold at reasonable prices"
"More than 3000 themes are available"
It's clearly a marketing stuff that doesn't have to be here in a dev doc.
I suggest that we will add "partner" marketplaces when foundation will be there and funded.

2021-10-13 09:29 UTC, jf-viguier commented
"Blocking this until a decision is made" I will wait, no problemo.
Prestashop employees are not neutral either, maybe you should ask external maintainers @PululuK @kpodemski ?

2021-10-13 10:05 UTC, kpodemski commented
@jf-viguier I'm a PrestaShop employee now.

2021-10-13 10:22 UTC, jf-viguier commented
@kpodemski congrats 👍

2021-10-13 15:15 UTC, ghost commented
I agree with @jf-viguier  we should put Prestashop 50 px and Okom3pom 3 px in the doc.

We have heard << PrestaShop (code) belongs to its authors >>, the same goes for the documentation.

For the moment PrestaShop SA contributes a lot but this is the purpose of the split

And I don't see the point of ads in the devdoc, in the user doc why not?

2021-10-14 09:12 UTC, eternoendless commented
> there are also other contributors (...), so they should be allowed to also advertise in the source code or documentation?

> I don't see the point of ads in the devdoc the user doc why not?

I think it _could_ be kept as informational, using a less marketing-y wording.

The real question is: should we banish all mentions to marketplaces from the docs? Or should we list them all? Perhaps only those of partners who contribute significantly to the project? Or just those that finance the (future) foundation? All arguments are valid, and are being actively discussed in order to find the most suitable solution.

And who makes that call?

Currently, the PrestaShop company has the final word on the project's decisions – as it's always been since the project was born. The problem with that is that we can't expect people to appropriate the project if it's tightly controlled by a benevolent dictator. That's why we are working to redefine the project's governance (i.e. how decisions are made and by whom) by stating clear rules under which the PrestaShop company continues to influence the project, but just as one actor among many. 

The governance question here is under which circumstances other actors can be allowed to join the influence group (i.e. the "foundation"). Naturally, we can't just make it so that anyone that walks through the door automatically gains the right to vote – that wouldn't make any sense. My personal view is that you must _earn_ your vote either by occupying a specific role in the project (e.g. a maintainer), or by financing the foundation.

As I said, these rules haven't been defined yet, which is why I don't want to rush into decisions. It doesn't necessarily mean the content will stay exactly as it is: perhaps it will be removed, changed to refer to a sponsor marketplace, or perhaps just listed among all other known marketplaces.

Rest assured that we want to make things right.

2021-10-14 14:20 UTC, jf-viguier commented
Thanks Pablo, I am confident, we are on the same track.
For now, I'll suggest another version for this pr.

2021-10-14 14:45 UTC, jf-viguier commented
@eternoendless and others friends, I've posted a new version with a cleaner and more objective point of view on addons. IMO the technical validation is the main argument of addons on a dev point of view and should be enforced the same way in others potentially listed marketplaces.
I've introduced others marketplaces and removed marketing bullshit.
WDYT ? Do I deserve a goodie from addons marketing team ? 😉

2021-10-14 14:59 UTC, matks commented
Thanks @jf-viguier but I think I heard some news that you will really love ;)

Waiting for @eternoendless confirmation but I think we got the GO to delete Addons stuff 🎉

2021-10-14 15:25 UTC, eternoendless approved these changes

2021-10-14 15:27 UTC, eternoendless commented
Looks good to me. It looks like we're going to progressively delete content related to the marketplace.

2021-10-15 09:37 UTC, matks reviewed
@jf-viguier We got the OK to remove the Addons link. Do you want to revert your PR to the initial change before we merge? Or do you want to keep the latest version?

2021-10-22 07:34 UTC, jf-viguier commented
Thanks @matks for this amazing decision, I've reverted and changed the last sentence, enjoy.

2021-10-22 07:52 UTC, matks approved these changes

2021-10-22 07:52 UTC, matks commented
Thanks for the revert @jf-viguier and it's now approved and merged

2021-10-22 07:52 UTC, merged