Update broken 404 links to github points 1.7.6.x -> 1.7.8.0
PrestaShop/docs pull request #1194
Opened 2021-10-20 19:40 UTC by SebSept

links to GitHub points to 1.7.6.x which doesn't exist anymore.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.x
| Description?  | 404 not found - fix links that points to 1.7.8.x branch instead of 1.7.6.x which is removed from GH
| Fixed ticket? | none

2021-10-21 07:41 UTC, matks requested changes
Hello !

Links to 1.7.6.x are broken because we deleted the 1.7.6.x branch. But I am not sure 1.7.8.x is a good replacement. One day we will delete 1.7.8.x branch too.

I suggest to rather use `tags` link:
https://github.com/PrestaShop/PrestaShop/blob/1.7.6.x
⬇️ 
https://github.com/PrestaShop/PrestaShop/blob/1.7.6.9

2021-10-21 16:53 UTC, SebSept commented
or maybe 1.7.8.0 ?
https://github.com/PrestaShop/PrestaShop/blob/1.7.8.0/classes/controller/FrontController.php

2021-10-23 20:46 UTC, matks commented
> or maybe 1.7.8.0 ? https://github.com/PrestaShop/PrestaShop/blob/1.7.8.0/classes/controller/FrontController.php

Could be, but as 1.7.6.x was used when this documentation was written, I am 100% sure the doc describes 1.7.6 situation well.

We can use 1.7.8.0 if we are 100% sure it properly illustrates this documentation section 😉

2021-10-23 21:17 UTC, SebSept commented
Right, I'll check that in a few days.

2021-10-25 12:41 UTC, Progi1984 commented
@SebSept Ping us after check.

2021-11-09 21:05 UTC, SebSept commented
Nothing serious and related to the `module` property has changed, since 2016 ... at least. 
PrestaShop version was 1.7.0.0 release candidate. Since mid 2020 (1.7.6 release), no changes except formating and licenses texts.
I also compared Controller.php (which hold the  `context` property) with a version before 1.7.6 and there is no changes related to `context`.

2021-11-10 21:27 UTC, matks approved these changes

2021-11-10 21:28 UTC, matks approved these changes

2021-11-10 21:29 UTC, matks commented
I updated the PR to use the 1.7.8.0 tag instead of 1.7.8.x branch. 1.7.8.x branch will be deleted in the future, 1.7.8.0 will not.

2021-11-10 21:29 UTC, matks commented
Thank you @SebSept

2021-11-10 21:29 UTC, merged

2021-11-10 21:30 UTC, matks commented
@SebSept Could you submit another PR to backport the changes to 8.x branch?

2021-11-10 22:14 UTC, SebSept commented
Thanks @matks, done for branch 8 -> #1208