Adding information for using TinyMCE editor and FormattedTextareaType with prestashop UI kit and twig form
PrestaShop/docs pull request #1308
Opened 2022-02-26 17:40 UTC by Rizzen59

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.x / 8.x
| Description?  | Please be specific when describing the PR. What did you add, why did you submit it?
| Fixed ticket? | Fixes #{issue number here} if there is a related issue

2022-02-26 17:43 UTC, Rizzen59 commented
I had to seach why my editor was not displayed (I found the solution by looking on Maintenance twig from) so to avoid other developers to loose time. I propose to improove documentation.

2022-02-28 10:40 UTC, matthieu-rolland reviewed
Thank you for your PR @Rizzen59 👍

2022-02-28 10:40 UTC, matthieu-rolland commented on development/components/form/types-reference/formatted-textarea.md
> +To use with twig and new prestashop admin UI Kit. You have to init the component :
To make it work in the PrestaShop UI Kit, you need to call the `TinyMCEEditor` js component :

2022-02-28 10:43 UTC, matthieu-rolland commented on development/components/form/types-reference/formatted-textarea.md
> +To use with twig and new prestashop admin UI Kit. You have to init the component :
```suggestion
To make it work in the PrestaShop UI Kit, you need to call the `TinyMCEEditor` js component:
```

2022-03-03 16:19 UTC, saulaski requested changes

2022-03-03 16:19 UTC, saulaski commented on development/components/form/types-reference/formatted-textarea.md
> +To use with twig and new prestashop admin UI Kit. You have to init the component :
Alternative wording:
```suggestion
In order to use TinyMCE editor in the PrestaShop UI Kit, you need to initialize its javascript component once the page is loaded:
```

2022-03-04 11:00 UTC, matthieu-rolland reviewed
hi @Rizzen59 !

you need to commit @saulaski 's wording and the PR is good to go 👍

2022-03-04 14:45 UTC, Rizzen59 commented
Thanks, i will make the change

2022-03-05 08:33 UTC, saulaski approved these changes

2022-03-07 07:59 UTC, NeOMakinG approved these changes

2022-03-08 08:09 UTC, Progi1984 approved these changes

2022-03-08 08:15 UTC, merged

2022-03-08 08:15 UTC, Progi1984 commented
Thanks @Rizzen59 

Could you create the same PR on 8.x branch ?