Functional checklist
PrestaShop/docs pull request #1368
Opened 2022-04-28 10:57 UTC by mariem-abid

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 8.x
| Description?  | Improve the **validation process** of the modules and themes on the **disneystore**.  The requests of "Sarah-Jane Le Corre" (Head of the care team)
| Fixed ticket? | no

2022-04-28 11:21 UTC, kpodemski reviewed
I think we might have a section helping module developers making sure their products work well, but Addons Marketplace is not an only markeplatce in PrestaShop ecosystem. This text shouldn't have any specifics required by it.

2022-04-28 11:21 UTC, kpodemski commented on module-theme-functional-checklist/_index.md
> +###Social Networks:
@mariem-abid this definitely doesn't apply to any best practices, etc. It's Addons Marketplace specific thing

2022-04-28 11:36 UTC, matks requested changes
Hello @mariem-abid I think indeed there is a misunderstanding ^^ this repository is not where such document should go.

I think it should go on www.prestashop.com or https://addons.prestashop.com/

2022-05-02 09:03 UTC, matks requested changes
Blocked while waiting for Steering Committee decision

https://github.com/PrestaShop/docs/pull/1369#issuecomment-1114640784

2022-06-06 21:10 UTC, matks commented
I close this as the linked contribution was closed https://github.com/PrestaShop/docs/pull/1369#issuecomment-1114640784

2022-06-06 21:10 UTC, closed without merging