Update migration.md
PrestaShop/docs pull request #1408
Opened 2022-07-10 20:51 UTC by LouisAUTHIE

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 8.x
| Description?  | link is broken 
| Fixed ticket? | n/a

2022-07-22 10:04 UTC, MeKeyCool requested changes

2022-07-22 10:04 UTC, MeKeyCool commented on basics/keeping-up-to-date/migration.md
> --   [Getting a list of all available ressources, ready for import/export](https://doc.prestashop.com/display/PS16/Web+service+one-page+documentation#Webserviceone-pagedocumentation-Availableresources
I don't understand, this link works for me :thinking: 
Maybe we should update it to [List of all available ressources](https://devdocs.prestashop.com/8/webservice/resources/) ?

2022-09-28 21:02 UTC, kpodemski commented on basics/keeping-up-to-date/migration.md
>  -   [Learning how-to use the webservice API](https://doc.prestashop.com/display/PS16/Using+the+PrestaShop+Web+Service)
```suggestion
-   [Learning how to use the webservice API]([web-service])

[web-service]: {{< ref "1.7/webservice" >}}
```

2022-09-28 21:03 UTC, kpodemski commented on basics/keeping-up-to-date/migration.md
> +-   [Learning how to use the webservice API]([web-service])
```suggestion
-   [Learning how to use the webservice API][web-service]
```

2022-09-28 21:03 UTC, kpodemski commented on basics/keeping-up-to-date/migration.md
> +[web-service]: {{< ref "1.7/webservice" >}}
```suggestion
[web-service]: {{< ref "8/webservice" >}}
```

2022-09-28 21:04 UTC, kpodemski commented on basics/keeping-up-to-date/migration.md
> +-   [Learning how to use the webservice API][web-service]
```suggestion
-   [How to use the webservice API][web-service]
```

2022-09-28 21:04 UTC, kpodemski approved these changes

2022-09-28 21:04 UTC, merged