Add Webservice tutorial in (Modules) extension concept section
PrestaShop/docs pull request #1410
Opened 2022-07-13 10:31 UTC by marsaldev

Add new page about how to extend the Webservice resources through custom entity and module

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.x
| Description?  | Chatting with a community member that needs to add informations accessible through webservice, I discover that there isn't a small tutorial on how to do through a module with a custom entity (using ObjectModel).
| Fixed ticket? | ~

2022-07-13 15:39 UTC, matthieu-rolland reviewed
that's a great addition 👍 

I made some feedback which I think make it easier to read

2022-07-13 15:39 UTC, matthieu-rolland commented on modules/concepts/webservice/_index.md
> +The follow is an example of correct configuration to load your entities in whatever folder you want.
```suggestion
The following is an example of a correct configuration to load your entities in whatever folder you want.
```

2022-07-13 15:39 UTC, matthieu-rolland commented on modules/concepts/webservice/_index.md
> +The `$webserviceParameters` is mandatory to define how and which fields to expose.
```suggestion
The `$webserviceParameters` array is mandatory to define how and which fields to expose.
```

2022-07-13 15:39 UTC, matthieu-rolland commented on modules/concepts/webservice/_index.md
> +The name to access to all the elements:
```suggestion
The key to access all the elements:
```

2022-07-13 15:39 UTC, matthieu-rolland commented on modules/concepts/webservice/_index.md
> +The name to access to the single element:
```suggestion
The key to access a single element:
```

2022-07-29 16:13 UTC, matks reviewed
Looks good to me, one last check from @kpodemski who knows better than me the topic and let's merge

2022-08-02 20:48 UTC, kpodemski commented
Thanks @marsaldev - I'll take a look this week ❤️

2022-08-04 08:39 UTC, Matt75 commented
Hello @marsaldev 

I'm not in favor to usage of namespace for classes that extends legacy PrestaShop Core classes like ObjectModel.

This classes were designed to be in the global namespace, use it with a namespace can create issues with others legacy classes, like native legacy logger : https://github.com/PrestaShop/PrestaShop/issues/28617

And also various others pieces of code that will interact with it in legacy PrestaShop core can encountered issues cause it were designed only for global namespace.

So my recommendation is to keep classes that's extends legacy PrestaShop core classes in global namespace, so put your ObjectModel in `modules/yourmodule/classes/Article.php`

All new classes that's not extends legacy classes can be namespaced and placed in `modules/yourmodule/src/` problem.

2022-08-16 11:13 UTC, kpodemski commented
Hi @marsaldev 

I agree with @Matt75. 

It's been reported a few times that having legacy classes hidden behind namespaces may be problematic in some undocumented scenarios. 

Let's keep it simple and focus on handling WS inside a class without having the composer handling autoloader, etc.

2022-08-16 11:14 UTC, kpodemski requested changes
Please drop the use of namespaces and composer

2022-08-16 13:29 UTC, marsaldev commented
Got it! 😉
I'll update it 👍🏻
Thanks a lot @Matt75 @kpodemski

2022-09-23 15:10 UTC, marsaldev reviewed
Done 😊
Looking forward your feedback(s)

2022-09-28 20:40 UTC, kpodemski commented on modules/concepts/webservice/_index.md
> +  );
```suggestion
    protected $webserviceParameters = array(
      'objectNodeName' => 'article',
      'objectsNodeName' => 'articles',
      'fields' => array(
          'title' => array('required' => true),
          'type' => array('required' => true),
          'content' => array(),
          'meta_title' => array(),
        )
    );
```

2022-09-28 20:40 UTC, kpodemski commented on modules/concepts/webservice/_index.md
> +### Register it through the addWebserviceResources hook
```suggestion
### Registration with a hook
```

2022-09-28 20:40 UTC, kpodemski commented on modules/concepts/webservice/_index.md
> +The hook `addWebserviceResources` must be registered by your module, usually done during the module installation.
```suggestion
The hook `addWebserviceResources` must be registered and implemented by your module.
```

2022-09-28 20:40 UTC, kpodemski commented on modules/concepts/webservice/_index.md
> +  ];
```suggestion
    return [
      'articles' => [
          'description' => 'Blog articles', // The description for those who access to this resource through WS
          'class' => 'Article', // The classname of your Entity
          'forbidden_method' => array('DELETE') // Optional, if you want to forbid some methods
      ]
    ];
```

2022-09-28 20:40 UTC, kpodemski commented on modules/concepts/webservice/_index.md
> +The following is an example of a correct configuration to load your entities in whatever folder you want.
```suggestion
The following is an example of a correct configuration to load your example entity to your module.
```

2022-09-28 20:40 UTC, kpodemski commented on modules/concepts/webservice/_index.md
> +include_once dirname(__FILE__).'/src/Entity/Article.php';
```suggestion
include_once _PS_MODULE_DIR_ . 'wsarticle/src/Entity/Article.php';
```

2022-09-28 20:40 UTC, kpodemski commented on modules/concepts/webservice/_index.md
> +include_once dirname(__FILE__).'/src/Entity/Article.php';
```suggestion
include_once _PS_MODULE_DIR_ . 'wsarticle/src/Entity/Article.php';
```

2022-09-28 20:40 UTC, kpodemski commented on modules/concepts/webservice/_index.md
> +            `meta-title` varchar(255) NOT NULL,
```suggestion
            `meta_title` varchar(255) NOT NULL,
```

2022-09-28 20:40 UTC, kpodemski commented on modules/concepts/webservice/_index.md
> +                'description' => 'Blog articles', // The description for who access to this resource through WS
```suggestion
                'description' => 'Blog articles', // The description for those who access to this resource through WS
```

2022-09-28 20:40 UTC, kpodemski commented on modules/concepts/webservice/_index.md
> +                'forbidden_method' => array('DELETE') // optional if you want to forbid some methods
```suggestion
                'forbidden_method' => array('DELETE') // Optional, if you want to forbid some methods
```

2022-09-28 20:40 UTC, kpodemski commented on modules/concepts/webservice/_index.md
> +Following the example above, the new resource will be available in the webservices resources list:
```suggestion
Following the example above, the new resource will be available in the webservice resources list:
```

2022-09-28 20:40 UTC, kpodemski commented on modules/concepts/webservice/_index.md
> +And will be accessible through your api url, plus the name that you've decided in `objectsNodeName`, for instance:
```suggestion
This new resource will be accessible through your API endpoint behind the name that you set in `objectsNodeName`, for instance:
```

2022-09-28 20:40 UTC, kpodemski commented on modules/concepts/webservice/_index.md
> +will give you something similar(in browser):
```suggestion
will return something similar to what you can see on the screenshot below (it is the XML response previewed in the browser):
```

2022-09-28 20:40 UTC, kpodemski commented on modules/concepts/webservice/_index.md
> +And something similar when you have articles in database:
```suggestion
And something like on the next screenshot, if you have articles in the database:
```

2022-09-28 20:42 UTC, kpodemski approved these changes

2022-09-28 20:42 UTC, merged

2022-09-28 20:43 UTC, kpodemski commented
Thank you, @marsaldev ❤️ I allowed myself to commit some minor improvements. Let's wait for the build to see how it looks, if it is ok we will need to have it in the PrestaShop 8 too :)