Add sendemail=1 to order_carriers endpoint
PrestaShop/docs pull request #1475
Opened 2022-08-31 13:58 UTC by jf-viguier

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 8.x
| Description?  | Add sendemail=1 to order_carriers endpoint
| Fixed ticket? | N/A

2022-08-31 21:36 UTC, PrestaEdit approved these changes

2022-09-02 19:55 UTC, kpodemski commented on webservice/getting-started.md
> +The `sendemail=1` parameter can be used on order_carriers endpoint to send the in transit email with the tracking number. Example : `http://example.com/api/order_carriers/12345?sendemail=1`
```suggestion
The `sendemail=1` parameter can be used on the `order_carriers` endpoint to send the _in-transit_ email with the tracking number. Example: `http://example.com/api/order_carriers/12345?sendemail=1`
```

Could you be more precise and describe what `12345` stands for?

2022-09-02 19:56 UTC, kpodemski requested changes
Feedback

2022-09-05 08:03 UTC, jf-viguier commented
@kpodemski it's done

2022-09-27 09:09 UTC, jf-viguier commented
@kpodemski ?

2022-09-28 14:43 UTC, kpodemski approved these changes

2022-09-28 14:43 UTC, merged

2022-09-28 14:44 UTC, kpodemski commented
Thanks, @jf-viguier, and sorry for the long waiting. A lot to do.

I guess it should be backported to 1.7.x? Let me know.