Fix references from develop to 1.7.8.0
PrestaShop/docs pull request #1508
Opened 2022-09-21 15:39 UTC by thomasnares

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.x
| Description?  | Replacement of all references to the PS repo from develop to 1.7.8.0 for 1.7.x doc

2022-09-21 18:26 UTC, kpodemski submitted a review, later dismissed
Thanks, @thomasnares 

A few things:
- ~It should be `1.7.8.x`~ it's ok to link to the tag, but I'm not sure if to `1.7.8.0` or recent version :-)
- please double-check if links with `#` point to the place in the code relevant to what is written

2022-09-21 18:34 UTC, kpodemski requested changes
Some changes are needed.

@eternoendless, shall we link to the most recently released version? e.g.: `1.7.8.7`?

2022-09-21 18:34 UTC, kpodemski commented on themes/reference/templates/notifications.md
> +Your front controller holds [the 4 following variables](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.0/classes/controller/FrontController.php#L616-L621):
Wrong link

2022-09-21 18:34 UTC, kpodemski commented on themes/reference/templates/notifications.md
> +Since PrestaShop 1.7, you can [redirect the customer AND display a message after an action](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.0/classes/controller/FrontController.php#L614-L633).
Wrong place in the code highlighted

2022-09-21 18:34 UTC, kpodemski commented on development/architecture/migration-guide/hooks.md
> +In ``classes/Hook``, find the [exec() function](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.0/classes/Hook.php#L733) and add the following code:
```suggestion
In ``classes/Hook``, find the [exec() function](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.0/classes/Hook.php#L766) and add the following code:
```

2022-09-26 16:45 UTC, eternoendless commented
> shall we link to the most recently released version? e.g.: `1.7.8.7`?

I think the latest .0 should do, unless the code is not yet present in that version. Otherwise we'd have to update all links whenever we publish a new patch version.

2022-09-28 21:10 UTC, kpodemski approved these changes

2022-09-28 21:10 UTC, merged

2022-09-28 21:10 UTC, kpodemski commented
Thanks @thomasnares :))