Add installation method module and remove duplicated doc from configuration
PrestaShop/docs pull request #1534
Opened 2022-10-06 08:59 UTC by thomasnares

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 8.x
| Description?  | Add installation methos from console, and remove duplicated doc from configuration

2022-10-07 09:00 UTC, kpodemski commented on modules/creation/tutorial.md
> +Let's examine each line :
```suggestion
Let's examine each line:
```

in English we don't need space before `:` 👍

2022-10-07 09:03 UTC, kpodemski commented on modules/creation/tutorial.md
>  This is a PrestaShop-specific object that allows to easily manage all the shop's settings. It stores its data on the `ps_configuration` database table.
```suggestion
This PrestaShop-specific object allows you to easily manage all the shop's settings. It stores its data on the `PREFIX_configuration` database table.
```

I think we can try to use `PREFIX_tablename` as it is recommended to use the custom prefix.

2022-10-09 19:45 UTC, matks approved these changes
Looks good to me 😄 

Just to be sure let's see @kpodemski final review

2022-10-11 08:12 UTC, kpodemski requested changes

2022-10-11 08:12 UTC, kpodemski commented on modules/creation/tutorial.md
> +You have two options to install a module : via back office interface, or via Symfony Console
```suggestion
You have two options to install a module: from the back office interface or using the Symfony Console component (CLI-base installation)
```

2022-10-11 08:12 UTC, kpodemski commented on modules/creation/tutorial.md
> +### Install module via back office interface
```suggestion
### Install module from the back office interface
```

2022-10-11 08:12 UTC, kpodemski commented on modules/creation/tutorial.md
> +### Install module via Symfony Console
```suggestion
### Install module from CLI using the Symfony Console component
```

2022-10-11 08:12 UTC, kpodemski commented on modules/creation/tutorial.md
> +Access your project's directory with a CLI, and run :
```suggestion
Access your project's directory with a CLI, and run:
```

2022-10-11 08:12 UTC, kpodemski commented on modules/creation/tutorial.md
> +To uninstall module, run :
```suggestion
To uninstall the module, run the following:
```

2022-10-11 09:45 UTC, thomasnares commented
Thanks @kpodemski 👍

2022-10-11 09:48 UTC, kpodemski approved these changes

2022-10-11 09:48 UTC, kpodemski commented
Thanks @thomasnares 

Let's backport it to 1.7 if you think it is relevant. Seems like it is, but it's worth checking if options are the same.

2022-10-11 09:53 UTC, merged