Update create-custom-column-type.md
PrestaShop/docs pull request #1597
Opened 2023-01-17 06:57 UTC by tivuno

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.x / 8.x
| Description?  | How to create custom column type for Symfony Grid controller

2023-01-17 07:19 UTC, thomasnares requested changes
Thanks @tivuno, i made a few suggestions 👍

2023-01-17 07:19 UTC, thomasnares commented on development/components/grid/tutorials/create-custom-column-type.md
> +It is highly likely that you are struggling to develop a module based on the new standards. You want to display some kind of data in a way not already predicted by the core team. No worries. Let's ha
```suggestion

You may need to display some kind of data in a specific format. This is how to do it: 
```

2023-01-17 07:19 UTC, thomasnares commented on development/components/grid/tutorials/create-custom-column-type.md
> +## Step 3. Define the respective .html.twig
```suggestion

## Step 3. Define the respective .html.twig
```

2023-01-17 07:19 UTC, thomasnares commented on development/components/grid/tutorials/create-custom-column-type.md
> +## Step 2. Use & call the new type
```suggestion

## Step 2. Use & call the new type

```

2023-01-17 07:19 UTC, thomasnares commented on development/components/grid/tutorials/create-custom-column-type.md
> +## Step 1. Define the new column type
```suggestion

## Step 1. Define the new column type

```

2023-01-17 07:19 UTC, thomasnares commented on development/components/grid/tutorials/create-custom-column-type.md
> +Create the following file:
```suggestion
Create the following file:

```

2023-01-17 07:19 UTC, thomasnares commented on development/components/grid/tutorials/create-custom-column-type.md
> +Let's assume that we need to make an html column to fire some js script.
```suggestion
Let's assume that we need to make an html column to display an object's ID within a `&lta>` html tag: 
```

2023-01-17 16:00 UTC, thomasnares approved these changes

2023-01-17 16:02 UTC, xiropot commented
@thomasnares Do I need to do anything else or its up to you now?

2023-01-17 16:03 UTC, thomasnares commented
looks good to me, lets wait another maintainer approval to merge it 👍 
thanks again

2023-01-18 14:47 UTC, matks approved these changes

2023-01-18 14:47 UTC, matks commented
Thank you @tivuno

2023-01-18 14:47 UTC, merged

2023-01-18 14:48 UTC, matks commented
@tivuno Would you consider submitting another PR to update `1.7.x` branch?

2023-01-18 17:53 UTC, tivuno commented
@matks i will do as soon as i find time. Even though i do believe its 99.99% the very same procedure.