Update upgrade.md
PrestaShop/docs pull request #1610
Opened 2023-02-13 19:27 UTC by alohapili

Links to the releases were broken. Changed it to release 8.0, but the preference might be to direct link to 1.7.7.5 - not sure. Putting latest for now since a working link is better than a broken one.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.x / 8.x
| Description?  | Please be specific when describing the PR. What did you add, why did you submit it?
| Fixed ticket? | Fixes #{issue number here} if there is a related issue

2023-02-16 08:38 UTC, 0x346e3730 requested changes

2023-02-16 08:38 UTC, 0x346e3730 commented on basics/keeping-up-to-date/upgrade.md
> +wget -O prestashop_8.0.1.zip https://github.com/PrestaShop/PrestaShop/releases/tag/8.0.1
This does not download the correct zipfile as it is the release page.

```suggestion
wget -O prestashop_8.0.1.zip https://github.com/PrestaShop/PrestaShop/releases/download/8.0.1/prestashop_8.0.1.zip
```

2023-02-16 08:38 UTC, 0x346e3730 commented on basics/keeping-up-to-date/upgrade.md
> +unzip prestashop_8.0.1.zip && unzip prestashop_8.0.1.zip
Why unzip twice the same file ? Before it was about unzipping two different files (one being the one downloaded in L39)

2023-03-17 13:12 UTC, kpodemski commented
Hello @alohapili 

Thank you for improving the page, but I'm closing this PR in favor of https://github.com/PrestaShop/docs/pull/1611 where we work on improving everything around upgrade content.

2023-03-17 13:12 UTC, closed without merging