Configuration form for module with symfony style
PrestaShop/docs pull request #1696
Opened 2023-07-17 19:09 UTC by thomasnares

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 8.x
| Description?  | Complete guide for a configuration page for a module

⚠️ Needs this PR to be merged : https://github.com/PrestaShop/ps-docs-theme/pull/41

2023-07-18 07:51 UTC, thomasnares commented
Fixes https://github.com/PrestaShop/docs/issues/1425

2023-07-18 09:42 UTC, kpodemski requested changes

2023-07-18 09:42 UTC, kpodemski commented on development/architecture/migration-guide/forms/_index.md
> +An almost complete reference of existing [Back Office types can be found here]({{<relref "/8/modules/creation/adding-configuration-page-modern#other-form-types">}}).
```suggestion
Reference of existing [back office form types can be found here]({{<relref "/8/modules/creation/adding-configuration-page-modern#other-form-types">}}). 
```

2023-07-18 09:42 UTC, kpodemski commented on modules/creation/adding-configuration-page-modern.md
> +In the first part of this guide, we will explain how to implement such a mecanism in a module. We will create a module, with a dedicated configuration page, with a simple configuration field.
```suggestion
In the first part of this guide, we will explain how to implement such a mechanism in a module. We will create a module with a dedicated configuration page consisting of a simple configuration field. 
```

2023-07-18 09:42 UTC, kpodemski commented on modules/creation/adding-configuration-page-modern.md
> +In the second part of this guide, we will list and illustrate the other form types (field types) availables.
```suggestion
```

This is no longer relevant, right?

2023-07-18 09:42 UTC, kpodemski commented on modules/creation/adding-configuration-page-modern.md
> +More informations about services in [Symfony official documentation](https://symfony.com/doc/4.4/service_container.html)
```suggestion
You can read more about services in the [official Symfony official documentation](https://symfony.com/doc/4.4/service_container.html)
```

2023-07-18 09:42 UTC, kpodemski commented on modules/creation/adding-configuration-page-modern.md
> +        return $return;
```suggestion
        $return = [];

        $return['config_text'] = $this->configuration->get(static::DEMO_SYMFONY_FORM_SIMPLE_TEXT_TYPE);

        return $return;
```

isn't it enough?

2023-07-18 09:42 UTC, kpodemski commented on modules/creation/adding-configuration-page-modern.md
> +        return [];
Let's add a simple validation. For example, if the field's length is longer than 32 chars, we throw an error.

2023-07-18 09:42 UTC, kpodemski commented on modules/creation/adding-configuration-page-modern.md
> +This Data configuration maps the `config_text` from the Form type to the `DEMO_SYMFONY_FORM_SIMPLE_TEXT_TYPE` configuration data key.
```suggestion
`DemoConfigurationTextDataConfiguration` maps the `config_text` from the Form Type to the `DEMO_SYMFONY_FORM_SIMPLE_TEXT_TYPE` configuration data key. 
```

wdyt?

2023-07-18 09:42 UTC, kpodemski commented on modules/creation/adding-configuration-page-modern.md
> +  prestashop.module.demosymfonyformsimple.form.demo_configuration_text_data_configuration:
Maybe better use `autowire`? 🤔

2023-07-18 09:42 UTC, kpodemski commented on modules/creation/adding-configuration-page-modern.md
> + * Provider ir responsible for providing form data, in this case it's as simple as using configuration to do that
```suggestion
 * Provider is responsible for providing form data, in this case, it is returned from the configuration component
```

how does it sound?

2023-07-18 09:42 UTC, kpodemski commented on modules/creation/adding-configuration-page-modern.md
> +  prestashop.module.demosymfonyformsimple.form.demo_configuration_text_form_data_provider:
autowire?

2023-07-18 09:42 UTC, kpodemski commented on modules/creation/adding-configuration-page-modern.md
> +For this form handler, we don't need to create a new class, we can use PrestaShop native's one.
I feel like it would be great to explain the magic underneath a bit more.

2023-07-18 09:42 UTC, kpodemski commented on modules/creation/adding-configuration-page-modern.md
> +            'demoConfigurationForm' => $textForm->createView(),
We could mention that in v8 you can also set the form theme from here.

2023-07-18 09:42 UTC, kpodemski commented on modules/creation/adding-configuration-page-modern.md
> +More informations about controllers on [Controller & routing]({{<relref "/8/development/architecture/modern/controller-routing">}}) and [Symfony official documentation](https://symfony.com/doc/4.4/co
```suggestion
You can read more about controllers in [controller & routing section]({{<relref "/8/development/architecture/modern/controller-routing">}}) and [in the official Symfony documentation](https://symfony.com/doc/4.4/controller.html)
```

2023-07-18 09:42 UTC, kpodemski commented on modules/creation/adding-configuration-page-modern.md
> +More informations about routing on [Controller & routing]({{<relref "/8/development/architecture/modern/controller-routing">}}) and [Symfony official documentation](https://symfony.com/doc/4.4/routin
Duplicate?

2023-07-18 09:42 UTC, kpodemski commented on modules/creation/adding-configuration-page-modern.md
> +      $route = SymfonyContainer::getInstance()->get('router')->generate('demo_configuration_form');
```suggestion
      $route = $this->get('router')->generate('demo_configuration_form');
```

That should do it.

2023-07-18 09:42 UTC, kpodemski commented on modules/creation/adding-configuration-page-modern.md
> +Go to the Back Office, and in Modules, find your module, then install and enable it.
```suggestion
Go to the Back Office, and in Modules Manager, find your module and install it. 
```

the module will be enabled after installation

2023-07-18 09:42 UTC, kpodemski commented on modules/creation/adding-configuration-page-modern.md
> +Some types requires Javascript initializations to properly work.
```suggestion
Some types require JavaScript component initialization to work correctly. 
```

2023-07-18 09:42 UTC, kpodemski commented on modules/creation/adding-configuration-page-modern.md
> +And add the Javascript code to this JS file:
```suggestion
And add the following JavaScript code to this file:
```

2023-07-18 09:42 UTC, kpodemski commented on modules/creation/adding-configuration-page-modern.md
> +And add the Javascript code to this JS file:
It's great that you mention it, but there's no direct correlation between your guide and this. Maybe if you limit the field length to 32 chars and use `TextWithLengthCounter`?

2023-07-18 09:42 UTC, kpodemski commented on modules/creation/adding-configuration-page-modern.md
> +The Javascript dependencies of specific types are [described in the Field's type reference]({{<relref "/8/development/components/form/types-reference">}})
```suggestion
The JavaScript dependencies of specific types are [described in the form types reference]({{<relref "/8/development/components/form/types-reference">}})
```

2023-07-18 09:42 UTC, kpodemski commented on modules/creation/adding-configuration-page-modern.md
> +Please refer to this example module for a complete implementation of those fields with Javascript: [DemoSymfonyForm](https://github.com/PrestaShop/example-modules/tree/master/demosymfonyform)
```suggestion
You can check this module to see an example of using JavaScript components: [DemoSymfonyForm](https://github.com/PrestaShop/example-modules/tree/master/demosymfonyform)
```

2023-07-18 09:42 UTC, kpodemski commented on modules/creation/adding-configuration-page.md
> +title: Legacy configuration page
```suggestion
title: Adding a configuration page (Legacy architecture)
```

2023-07-19 15:51 UTC, thomasnares commented on modules/creation/adding-configuration-page-modern.md
> +  prestashop.module.demosymfonyformsimple.form.demo_configuration_text_data_configuration:
can you show me ? not sure i can do it

2023-07-19 15:51 UTC, thomasnares commented on modules/creation/adding-configuration-page-modern.md
> +  prestashop.module.demosymfonyformsimple.form.demo_configuration_text_form_data_provider:
same, can you show me how you would simplify ?

2023-07-19 15:52 UTC, thomasnares commented on modules/creation/adding-configuration-page-modern.md
> +            'demoConfigurationForm' => $textForm->createView(),
can you point me to this feature ? not sure i understand this one

2023-07-25 15:09 UTC, kpodemski approved these changes

2023-07-25 15:10 UTC, merged