Allow .well-known directory (pki validation / letsencrypt)
PrestaShop/docs pull request #1724
Opened 2023-09-09 05:17 UTC by BarbUk

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 8.x
| Description?  | Fix nginx example configuration to allow .well-known directory usage, which is used for pki validation or acme / letsencrypt
| Fixed ticket? | no

2023-09-09 05:23 UTC, BarbUk commented
The same modification should be done to the 1.7 branch.
Should I make another PR ?

2023-09-11 12:59 UTC, matks commented
> The same modification should be done to the 1.7 branch. Should I make another PR ?

Usually we first merge the PR on 8.x **then we create another PR** and use `git cherry-pick` to backport the commit

2023-09-11 13:35 UTC, jokesterfr commented
Hi there!
It's interesting to mention nginx can be bound to let's encrypt, but I'm not sure this is relevant as the default example for PrestaShop. 

Don't get me wrong, this improvement could be provided as a secondary integration example, but you never know the will of the user integrating nginx + prestashop. Use cases are very wide, it could be placed behind another reverse-proxy taking care of the HTTPS, or any other http component... Better not document (and maintain) what is not closely relevant to PrestaShop IMO.

2023-09-11 13:46 UTC, matks requested changes
I'm not a NGINX expert but I trust @jokesterfr on this topic 👍 

The developer documentation of PrestaShop must act as a standard guide for prestashop newcomers so we can only add in it generic and standard information, we can't push side-cases

2023-09-11 15:57 UTC, BarbUk commented
Letsencrypt is one of the [many services](https://en.m.wikipedia.org/wiki/Well-known_URI) that use a well-known dir. 

Usage of this ressource is documented in [RFC 8615](https://datatracker.ietf.org/doc/html/rfc8615).

You document a configuration that explicitly deny usage of this directory. It should not be blocked by default IMHO.

2023-09-12 06:33 UTC, thomasnares commented
Hi @BarbUk, i suggest moving your example to: https://devdocs.prestashop-project.org/8/scale/webservers/nginx/

- the page "installation" is more about local environment than internet exposed PS instance; 
- the page "Optimize your nginx configuration" is more about going to production, so it makes sense to mention .well-known here. 

You could create a heading and show your code snippet 👍

2023-09-12 07:05 UTC, matks commented
Great suggestion from @thomasnares

2023-09-12 09:56 UTC, BarbUk commented
Thanks for the suggestion @thomasnares.
I've updated the PR.

2023-09-12 12:11 UTC, thomasnares approved these changes
Thanks @BarbUk, i just added some majs on the brands/services

2023-09-12 12:11 UTC, thomasnares commented on scale/webservers/nginx.md
> +### Allow usage of `.well-known` directory (letsencrypt/pki validation, apple pay)
```suggestion
### Allow usage of `.well-known` directory (Let's Encrypt / PKI validation, Apple Pay)
```

2023-09-12 12:58 UTC, matks approved these changes

2023-09-13 08:44 UTC, merged

2023-09-13 08:44 UTC, kpodemski commented
thank you @BarbUk !