Specific vertion of PS where it is available
PrestaShop/docs pull request #1757
Opened 2023-11-27 13:15 UTC by msaustral

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.x / 8.x
| Description?  | Please be specific when describing the PR. What did you add, why did you submit it?
| Fixed ticket? | Fixes #{issue number here} if there is a related issue

2023-11-27 14:12 UTC, thomasnares reviewed
Hi @msaustral, thanks for your contribution, i left you a comment 👍 

Can you put it on the H1 line of the page (line 7)

2023-11-27 14:12 UTC, thomasnares commented on development/components/form/types-reference/number-min-max-filter.md
> +ONLY AVAILABLE FROM PS 1.7.7.X ->
We should not indicate this information here, but in the first heading of the page, with the specific markdown

```
{{< minver v="1.7.7" >}}
```

2023-12-05 06:53 UTC, kpodemski requested changes
Hello @msaustral 

Please follow @thomasnares suggestions.

2023-12-13 16:45 UTC, kpodemski commented
We have this information in ps8 docs, I think we can close this one.

2023-12-13 16:45 UTC, closed without merging