Specific version of PS where it is available
PrestaShop/docs pull request #1758
Opened 2023-11-27 15:09 UTC by msaustral

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.x / 8.x
| Description?  | Please be specific when describing the PR. What did you add, why did you submit it?
| Fixed ticket? | Fixes #{issue number here} if there is a related issue

2023-11-28 13:51 UTC, tleon approved these changes

2023-11-28 14:20 UTC, thomasnares reviewed
Thanks @msaustral, it should be like this (my suggestion)

2023-11-28 14:20 UTC, thomasnares commented on development/components/form/types-reference/number-min-max-filter.md
> +<h1>Available from PS 1.7.7.x and UP</h1>
```suggestion
```

2023-11-28 14:20 UTC, thomasnares commented on development/components/form/types-reference/number-min-max-filter.md
>  # NumberMinMaxFilterType
```suggestion
# NumberMinMaxFilterType {{< minver v="1.7.7.x" title="true" >}}
```

2023-12-05 06:53 UTC, kpodemski requested changes
Hello @msaustral 

Please follow @thomasnares suggestions.

2023-12-05 13:26 UTC, thomasnares approved these changes
thanks @msaustral 👍

2023-12-05 14:14 UTC, kpodemski approved these changes

2023-12-05 14:14 UTC, merged