Introduce Flashlight to devdocs
PrestaShop/docs pull request #1761
Opened 2023-12-04 17:06 UTC by thomasnares

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 8.x
| Description?  | Introduce Flashlight to devdocs

2023-12-04 17:07 UTC, thomasnares commented
@jokesterfr you may have remarks or important notes to add to this page, or let me know and i add them 👍

2023-12-05 07:14 UTC, matthieu-rolland approved these changes
looks good to me 👍 let's wait for @jokesterfr 's point of view

2023-12-05 14:42 UTC, kpodemski commented on basics/installation/advanced/prestashop-flashlight.md
> +Looking for production grade images ?
```suggestion
Are you looking for production-grade images? 
```

2023-12-05 14:42 UTC, kpodemski commented on basics/installation/advanced/prestashop-flashlight.md
> +This installation method is not for production and should not be exposed to public traffic over internet,
```suggestion
This installation method is not for production and should not be exposed to public traffic over the internet,
```

2023-12-05 14:42 UTC, kpodemski commented on basics/installation/advanced/prestashop-flashlight.md
> +- Install docker Compose
```suggestion
- Install Docker Compose
```

2023-12-05 14:42 UTC, kpodemski commented on basics/installation/environments/docker.md
> +Looking for a quicker way to test and develop on PrestaShop ?
```suggestion
Looking for a quicker way to test and develop on PrestaShop?
```

2023-12-05 14:42 UTC, kpodemski commented on basics/installation/environments/docker.md
> +PrestaShop provides two options when it comes to run it with Docker:
```suggestion
PrestaShop provides two options when it comes to running it with Docker:
```

2023-12-05 14:42 UTC, kpodemski commented on basics/installation/environments/docker.md
> +- Development and testing friendly images with tooling : PrestaShop Flashlight.
```suggestion
- Development and testing friendly images with tooling: PrestaShop Flashlight.
```

2023-12-05 15:00 UTC, kpodemski commented
Hi @jokesterfr 

Can you please verify if everything is alright?

2023-12-07 09:25 UTC, cdesiles commented on basics/installation/advanced/prestashop-flashlight.md
> +cp .env.dist .env
It could still work, but I would suggest using examples rather than the default docker-compose.yml given

2023-12-07 11:09 UTC, jokesterfr commented on basics/installation/advanced/prestashop-flashlight.md
> +cp .env.dist .env
See: https://github.com/PrestaShop/prestashop-flashlight/pull/41

2023-12-07 16:25 UTC, kpodemski commented on basics/installation/advanced/prestashop-flashlight.md
> +cp .env.dist .env
@thomasnares Clement's idea is to mention things from the PR above instead 👍🏻

2023-12-07 16:25 UTC, kpodemski requested changes
@jokesterfr feedback to be applied

2023-12-18 13:51 UTC, thomasnares commented
Added the example for module dev here: https://github.com/PrestaShop/prestashop-flashlight/pull/49

2023-12-19 07:51 UTC, kpodemski approved these changes

2023-12-19 07:51 UTC, merged