Update upgrade.md
PrestaShop/docs pull request #1844
Opened 2024-07-13 10:28 UTC by sebastian-marinescu

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.x
| Description?  | Better download instructions

2024-07-16 15:20 UTC, nicosomb requested changes
I think it's better to update the lines about PS 1.7.7.5 to replace it with the last release.

2024-07-16 18:33 UTC, sebastian-marinescu commented
Okay, done 👍

2024-07-17 05:27 UTC, nicosomb approved these changes

2024-07-22 09:00 UTC, kpodemski approved these changes

2024-07-22 09:00 UTC, merged

2024-07-22 09:00 UTC, kpodemski commented
thank you @sebastian-marinescu