feat: rebranding docs
PrestaShop/docs pull request #1856
Opened 2024-08-07 13:03 UTC by tblivet

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 9.x
| Description?  | Docs for BO rebranding
| Fixed ticket? |

2024-08-09 12:55 UTC, kpodemski commented
Hello @tblivet @jolelievre 

Part of this content looks like it should be shared on the Build Blog, and another part looks like something we should put in "Notable changes" in the documentation, some is a generic information about CSS variables and something that could be part of the PrestaShop UI Kit repo only. I see three items:

## First

Files:
- development/rebranding/themes.md
- development/rebranding/ui-kit-v2/why.md
- development/rebranding/ui-kit-v2/css-variables.md

are good material for an article on the build blog or to the "second" point on this list.

## Second
Files:
- development/rebranding/ui-kit-v2/variables-reference.md
- development/rebranding/ui-kit-v2/how-to-use-it.md
- development/rebranding/ui-kit-v2/css-variables.md 

are good content for https://devdocs.prestashop-project.org/8/development/uikit/

## Third
Files:
- development/rebranding/introduction.md
- development/rebranding/breaking-changes.md

Something that should go to the Notable Changes.

Let me know what you think.

2024-08-09 12:58 UTC, kpodemski requested changes

2024-08-09 12:58 UTC, kpodemski commented on development/rebranding/_index.md
> +useMermaid: true
no need to load mermaid if you don't use mermaid 😎

2024-08-23 14:15 UTC, tblivet commented
Hi @kpodemski and @jolelievre,
Based on your comments and other feedback, I have made some changes to make the documentation less narrative and more technical. I will include more narrative content in a separate blog post, as you suggested. I agree, it's a good idea to provide information in a post.

2024-09-02 12:32 UTC, kpodemski requested changes
Here's the review. I added some suggestions.

2024-09-02 12:32 UTC, kpodemski commented on development/core-updates/9.0/bo-rebrand.md
> +title: BO rebranding
You can put this content inside the Notable Changes page that already exists:
https://devdocs.prestashop-project.org/9/modules/core-updates/9.0/

You can create a new section, "Back office rebranding", at the end of this page.

2024-09-02 12:32 UTC, kpodemski commented on development/core-updates/9.0/breaking-changes.md
> +title: BO breaking changes
This content should be part of the existing notable changes page.

2024-09-02 12:32 UTC, kpodemski commented on development/core-updates/_index.md
> +title: Core changes
Not needed page.

2024-09-02 12:32 UTC, kpodemski commented on development/ui-kit/uikit.md
>  ---
I think you need to leave this page and create an alias, so that the old page will point to the new page.

2024-09-02 12:32 UTC, kpodemski commented on development/ui-kit/css-variables.md
> +# Introducing CSS variables
```suggestion
# CSS variables in PrestaShop UI Kit
```

2024-09-02 12:32 UTC, kpodemski commented on development/ui-kit/css-variables.md
> +CSS Variables for Design Harmonization in the Back Office.
```suggestion
PrestaShop UI Kit uses CSS variables for design harmonization in the back office.
```

2024-09-02 12:32 UTC, kpodemski commented on development/ui-kit/how-to-use-it.md
> +# How to use new set of CSS variables ?
```suggestion
# How to use a new set of CSS variables?
```

2024-09-02 12:32 UTC, kpodemski commented on development/ui-kit/how-to-use-it.md
> +title: How to use it ?
```suggestion
title: How to use it?
```

2024-09-02 12:32 UTC, kpodemski commented on development/ui-kit/how-to-use-it.md
> +To maintain consistency across the PrestaShop back office, CSS variables have been introduced in `_root.scss`. This guide explains how to use these variables in PrestaShop.
```suggestion
To maintain consistency across the PrestaShop back office, CSS variables have been introduced in `_root.scss`. This guide explains how to use them.
```

2024-09-02 12:32 UTC, kpodemski commented on development/ui-kit/how-to-use-it.md
> +## Using CSS variables with v9 and higher
```suggestion
## Using CSS variables in PrestaShop 9.0+
```

2024-09-02 12:32 UTC, kpodemski commented on development/ui-kit/how-to-use-it.md
> +In PrestaShop v9 and higher, use the CSS variables introduced in `_root.scss` for consistent styling in the Back Office.
```suggestion
In PrestaShop v9 and later, we use the CSS variables introduced in `_root.scss` for consistent styling in the back office.
```

2024-09-02 12:32 UTC, kpodemski commented on development/ui-kit/how-to-use-it.md
> +- Refer to `_root.scss` for the latest <a href="https://github.com/PrestaShop/prestashop-ui-kit/blob/develop/scss/_root.scss" target="_blank">list of available variables</a>.
Here I think you should use `refrel` to the docs page you created, right?

2024-09-16 12:31 UTC, tblivet commented
Hi @kpodemski, I have just added your suggestions. Is it okay for you?

2024-09-18 09:25 UTC, kpodemski approved these changes

2024-09-18 09:25 UTC, kpodemski commented
love it, thank you @tblivet !

2024-09-18 09:25 UTC, merged

2024-09-18 19:19 UTC, matks commented
Thank you @tblivet 😄