Remove impossible Ping
PrestaShop/docs pull request #1889
Opened 2024-11-25 19:02 UTC by Touxten

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 8.x 
| Description?  | We can't ping team as a kidam
| Fixed ticket? |
| Sponsor company   | @friends-of-presta 

Can you add cherry pick for remember

2024-11-25 19:10 UTC, Touxten commented
@PrestaShop/Committers

2024-11-26 10:01 UTC, kpodemski commented
@Touxten you just pinged committers, so... why is it not possible? 🤔

2024-11-26 10:04 UTC, Hlavtox commented
@kpodemski Maybe he thought that it's not working because nobody ever responds. :D :D

2024-11-26 10:04 UTC, kpodemski commented
@Hlavtox, why are you not responding then? :(

2024-11-26 10:06 UTC, Touxten commented
This is not possible for users who are not in Team PrestaShop ( commiter maintener ... ) 

Create a new github User and try  @PrestaShop/Committers

2024-11-26 10:10 UTC, Touxten commented
When I was a commiter, I could do it.

Here people think they've contacted you, but they haven't, so it's frustrating.

2024-11-26 10:13 UTC, kpodemski requested changes
ok, I'm blocking this for now, we need to figure out how to improve the process 😱

2024-11-26 10:31 UTC, Touxten commented
I've already tried in the github options on the Repo Friends of Presta where we have teams and it's not possible.
It's only for members of the organization.

If you find a way i am happy

2024-11-26 14:55 UTC, matks commented
Hi @Touxten can you ping @PrestaShop/prestashop-core-developers ? Or @prestashop/maintainers ?

2024-11-26 14:56 UTC, Touxten commented
@PrestaShop/prestashop-core-developers

2024-11-26 14:58 UTC, Touxten commented
No :'( i try with my team you can't ping a team of an organisation if you are not inside.

i can change my PR with a link : https://www.prestashop-project.org/project-organization/people-and-roles/

2024-12-05 08:58 UTC, kpodemski commented
@Touxten let's use the link and mention that you can ping some committers, not ideal but seems there's no other way

2024-12-05 10:03 UTC, Touxten commented
@kpodemski i change my Pr but my english is bas i hope it's ok now

2025-02-13 08:58 UTC, kpodemski approved these changes

2025-02-13 09:03 UTC, kpodemski approved these changes

2025-02-13 09:04 UTC, kpodemski commented
thank you very much @Touxten 

I rebased the PR and adjusted the text following your suggestion

2025-02-13 09:07 UTC, merged