Explain the bridge between SF and legacy hooks
PrestaShop/docs pull request #661
Opened 2020-08-17 16:47 UTC by matks

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Explain the bridge between SF and legacy hooks

2020-08-18 08:53 UTC, matks commented
PR ready for review

2020-08-18 11:34 UTC, jolelievre commented on src/content/1.7/development/architecture/legacy/hooks.md
> +The modules which have previously subscribed to this hook will be called and will be able act on this hook. Depending on the hook nature, they can alter the data being passed, trigger an event of eve
```suggestion
The modules which have previously subscribed to this hook will be called and will be able to act on this hook. Depending on the hook nature, they can alter the data being passed, trigger an event or even return a result (a data structure or raw HTML) to be used within PrestaShop.
```

2020-08-18 11:38 UTC, jolelievre commented on src/content/1.7/development/architecture/legacy/hooks.md
> +Then it will create as many event subscriptions as there are hooks, following a naming convention.
```suggestion
Then it will create as many event subscriptions as there are hooks, following a naming convention based on database IDs.
```

2020-08-18 11:38 UTC, jolelievre commented on src/content/1.7/development/architecture/legacy/hooks.md
> +For example if module 267 has subscribed to hook 82, LegacyHookSubscriber will create a subscription `call_82_267`.
```suggestion
For example if module with `id_module` 267 has subscribed to hook with `id_hook` 82, `LegacyHookSubscriber` will create a subscription `call_82_267`.
```

2020-08-18 11:44 UTC, jolelievre commented on src/content/1.7/development/architecture/legacy/hooks.md
> +Using a dedicated magic method `__call()`, the LegacyHookSubscriber will track which hook has been called and trigger the related `Hook::exec()` call.
```suggestion
Using a dedicated magic method `__call()`, the `LegacyHookSubscriber` will parse the called method (ex: `call_82_267`) to retrieve the appropriate hook and module (using their respective IDs) and trigger the related `Hook::exec()` call with the appropriate parameters.
```

2020-08-19 09:23 UTC, matks commented
> I think this article should be split in two:
> 
> The first part should describe Hooks as a [PrestaShop component](https://devdocs.prestashop.com/1.7/development/components/).
> 
> The second one could be a subsection of the other page, explaining how the bridge between events and hooks works. A link to this article should be added [here](https://devdocs.prestashop.com/1.7/development/architecture/migration-guide/hooks/#dispatching-hooks-using-the-hook-dispatcher) as welll

Done in https://github.com/PrestaShop/docs/pull/661/commits/0691892c8df4a4abef4f1b5edb73030286fa656d

- new "Hooks component" section
- new "Symfony bridge for hooks" page in this section
- links to Hook concept now target this section
- I also moved "Register a new hook" how-to into this section and added an alias to preserve URL

2020-08-19 16:05 UTC, eternoendless requested changes

2020-08-19 16:05 UTC, eternoendless commented on src/content/1.7/development/components/hooks/symfony-bridge.md
> +For example if module with `id_module` 267 has subscribed to hook with `id_hook` 82, `LegacyHookSubscriber` will create a subscription `call_82_267`.
```suggestion
For example, if module with `id_module` 267 has subscribed to hook with `id_hook` 82, `LegacyHookSubscriber` will create a subscription `call_82_267`.
```

2020-08-19 16:05 UTC, eternoendless commented on src/content/1.7/development/components/hooks/symfony-bridge.md
> +When a hook is dispatched inside Symfony-powered pages of the Back-office, the HookDispatcher dispatches the hook similarly to a regular Symfony event, and this event is being listened to by LegacyHo
```suggestion
When a hook is dispatched inside Symfony-powered controllers, `HookDispatcher` dispatches the hook similarly to a regular Symfony event; this event is being listened to by `LegacyHookSubscriber` who will then trigger the related `Hook::exec()` call.
```

2020-08-19 16:16 UTC, matks commented on src/content/1.7/development/components/hooks/_index.md
> +The main path for Module integration is Hooks, which are placed throughout the system. Modules can subscribe to hooks in order to provide or alter features.
For the record 😛  I stole these words from yourself in https://build.prestashop.com/news/prestashop-in-2019-and-beyond-part-1-current-architecture/

2020-08-19 16:27 UTC, eternoendless commented on src/content/1.7/development/components/hooks/_index.md
> +The main path for Module integration is Hooks, which are placed throughout the system. Modules can subscribe to hooks in order to provide or alter features.
You forgot that I had written this two paragraphs before 😉

> The Modules system provides a plug-in approach to added functionality. As explained before, it relies mainly on specified extension points called “Hooks”

2020-08-20 07:30 UTC, matks commented on src/content/1.7/development/components/hooks/register-new-hook.md
> +    {s
Ouuups

2020-08-20 13:30 UTC, matks commented on src/content/1.7/modules/concepts/hooks/_index.md
> +[hooks-component]: {{< ref "/1.7/development/components/hooks/_index.md" >}}
```suggestion
[hooks-component]: {{< ref "/1.7/development/components/hook/_index.md" >}}
```

2020-08-20 13:31 UTC, matks commented on src/content/1.7/development/architecture/migration-guide/hooks.md
> +[hooks-component]: {{< ref "/1.7/development/components/hooks/_index.md" >}}
```suggestion
[hooks-component]: {{< ref "/1.7/development/components/hook/_index.md" >}}
```

2020-08-20 13:37 UTC, matks commented
@eternoendless All feedbacks have been applied. Unfortunately github is behaving in weird ways right now, so I had to apply feedbacks in small batches as my "apply suggestions". That created multiple git commits so I squashed all that.

2020-08-20 15:18 UTC, eternoendless requested changes

2020-08-20 15:18 UTC, eternoendless commented on src/content/1.7/development/components/hook/_index.md
> +## Modules callback
```suggestion
## Module callback
```

2020-08-20 15:18 UTC, eternoendless commented on src/content/1.7/development/components/hook/register-new-hook.md
>  weight: 60
```suggestion
weight: 10
```

2020-08-20 15:18 UTC, eternoendless commented on src/content/1.7/development/components/hook/symfony-bridge.md
> +title: Symfony bridge for hooks
```suggestion
title: Symfony bridge for hooks
weight: 20
```

2020-08-20 15:18 UTC, eternoendless commented on src/content/1.7/development/components/hook/symfony-bridge.md
> +It is important that modules which subscribe to a hook are correctly notified no matter where the hook is dispatched form, be it in legacy code or modern code.
```suggestion
It is important that modules which subscribe to a hook are correctly notified no matter where the hook is dispatched from, be it in legacy code or modern code.
```

2020-08-20 15:19 UTC, eternoendless approved these changes

2020-08-20 15:21 UTC, eternoendless commented
Closed/reopened to trigger Travis

2020-08-20 15:22 UTC, eternoendless commented
Thanks @matks

2020-08-20 15:22 UTC, merged

2020-08-20 15:24 UTC, matks commented
🤩