Added hook actionProductImageDeleted to docs
PrestaShop/docs pull request #957
Opened 2021-04-23 02:00 UTC by arouiadib

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Add the hook actionProductImageDeleted to the list of hooks in docs.
| Fixed ticket? | N/A

2021-04-23 07:09 UTC, Progi1984 commented on src/content/1.7/modules/concepts/hooks/list-of-hooks.md
> +
```suggestion
    ```
```

2021-04-23 07:10 UTC, Progi1984 commented on src/content/1.7/modules/concepts/hooks/list-of-hooks.md
> +    -  controllers/admin/AdminProductsController.php
```suggestion
    Located in: controllers/admin/AdminProductsController.php
```

2021-04-23 17:50 UTC, arouiadib commented
Thanks @Progi1984 for CR

2021-04-25 00:23 UTC, PululuK approved these changes
Thank you @arouiadib 
It is Ok for me ... Waiting for https://github.com/PrestaShop/PrestaShop/pull/24051 merge

2021-04-25 00:23 UTC, PululuK requested changes
Merge after https://github.com/PrestaShop/PrestaShop/pull/24051

2021-04-26 08:41 UTC, NeOMakinG approved these changes
Approving in order to make it mergeable when PS PR is merged :)

2021-08-05 16:32 UTC, matks commented
Hello,

I have modified your PR to target the `1.7.x` branch.

We have modified the devdocs inner working in order to welcome multiple documentation versions. This is because soon we will have a 1.7 documentation and a 8.0 documentation, matching PrestaShop 1.7 or PrestaShop 8.0 softwares.

Read more on https://devdocs.prestashop.com/1.7/contribute/documentation/how/documentation-versions/

Please also note that now that we have multiple versions inside one documentation, we had to build a workflow that can handle this setup. This repository https://github.com/PrestaShop/docs now only contains the content of the documentation, and https://github.com/PrestaShop/devdocs-site contains the sources and the deployment workflow.

Because of this, some files have moved and you might have to rebase your Pull Request to match the new structure of the repository.

2021-08-10 10:16 UTC, eternoendless commented
I have changed the branch to target 8.x as the PR is not yet merged

2021-08-10 10:16 UTC, eternoendless commented on src/content/1.7/modules/concepts/hooks/list-of-hooks.md
> +    Available since: {{< minver v="1.7.8" >}}
```suggestion
    Available since: {{< minver v="8.0" >}}
```

2021-08-11 06:56 UTC, Progi1984 approved these changes

2021-08-11 06:56 UTC, Progi1984 commented
@arouiadib Thank you for your contribution. Could you rebase your PR ?

2022-02-02 10:32 UTC, PierreRambaud commented
The PR has been closed, I'm closing it since it depends on it.

2022-02-02 10:32 UTC, closed without merging